class_names = {
    "Brown Spot Disease": 0,
    "Dirty Panicle Disease": 0,
    "Groundnut_Late_leaf_spot": 0,
    "Groundnut_Rust": 0,
    "Narrow Brown Spot Disease": 0,
    "Rice Blast Disease": 0,
    "Rice-Blast-Disease": 0,
    "Rice_Bacterial_Blight": 0,
    "Rice_Brown_spot": 0,
    "Tomato_Botrytis": 0,
    "Tomato_Early_Blight": 0,
    "Wheat_Loose_mut": 0,
    "Wheat_Steam_rust": 0,
    "bercak_coklat": 0,
    "blas": 0,
    "brown_spot_disease": 0,
    "dirty_panicle_disease": 0,
    "early stage": 0,
    "harvesting stage": 0,
    "hawar_daun_bakteri": 0,
    "mid age": 0,
    "mid satge": 0,
    "mid stage": 0,
    "narrow_brown_spot_disease": 0,
    "rice": 0,
    "rice_blast_disease": 0,
    "tungro": 0,
    "Brown Spot Area": 0
}