
class_names = {
    0: 'Brown Spot Disease',
    1: 'Dirty Panicle Disease',
    2: 'Groundnut_Late_leaf_spot',
    3: 'Groundnut_Rust',
    4: 'Narrow Brown Spot Disease',
    5: 'Rice Blast Disease',
    6: 'Rice-Blast-Disease',
    7: 'Rice_Bacterial_Blight',
    8: 'Rice_Brown_spot',
    9: 'Tomato_Botrytis',
    10: 'Tomato_Early_Blight',
    11: 'Wheat_Loose_mut',
    12: 'Wheat_Steam_rust',
    13: 'bercak_coklat',
    14: 'blas',
    15: 'brown_spot_disease',
    16: 'dirty_panicle_disease',
    17: 'early stage',
    18: 'harvesting stage',
    19: 'hawar_daun_bakteri',
    20: 'mid age',
    21: 'mid satge',
    22: 'mid stage',
    23: 'narrow_brown_spot_disease',
    24: 'rice',
    25: 'rice_blast_disease',
    26: 'tungro',
    27: 'Brown Spot Area'
}
